export type ITransportMatching = {
  id: number;
  trans_type: number;
  created_user: string;
  created_date: string;
  updated_user: string;
  updated_date: string;
  carrier_operator_id: string;
  shipper_operator_id: string;
  carrier_operator_code: string;
  shipper_operator_code: string;
  shipper_operator_name: string;
  carrier_operator_name: string;
  carrier2_operator_id: string | null;
  carrier2_operator_code: string | null;
  batch_id: number;
  cns_line_item_by_date_id: number;
  vehicle_avb_resource_item_id: number;
  trailer_number: number;
  departure_from: number;
  arrival_to: number;
  transport_date: string;
  transport_code: string;
  status: number;
  request_snapshot: {
    id: number;
    status: number;
    weight: number | null;
    arrival_to: number;
    trans_type: number;
    operator_id: string;
    total_width: number | null;
    total_height: number | null;
    total_length: number | null;
    operator_code: string | null;
    departure_from: number;
    price_per_unit: number;
    trailer_number: number;
    trans_order_id: string | null;
    transport_code: string;
    transport_name: string;
    collection_date: string;
    cns_line_item_id: number | null;
    transport_plan_id: number | null;
    trans_plan_id: string | null;
    vehicle_condition: string | null;
    collection_time_to: string;
    outer_package_code: number;
    trailer_number_rest: number;
    collection_time_from: string;
    req_cns_line_item_id: number | null;
    special_instructions: string | null;
    temperature_range: string[];
  };
  propose_snapshot: {
    id: number;
    day: string;
    giai: string | null;
    price: number;
    status: number;
    trip_name: string;
    arrival_to: number;
    cut_off_time: number;
    cut_off_fee: number;
    cut_off_info_id: number;
    assign_type: string | null;
    max_payload: number | null;
    operator_id: string;
    total_width: number;
    arrival_time: string;
    arrival_date: string;
    total_height: number;
    total_length: number;
    vehicle_size: string | null;
    vehicle_type: string | null;
    display_order: number | null;
    operator_code: string | null;
    departure_from: number;
    departure_date: string;
    adjustment_price: number | null;
    temperature_range: string[];
    departure_time_max: string;
    departure_time_min: string;
    vehicle_diagram_id: string | null;
    vehicle_avb_resource_id: string | null;
    car_max_load_capacity1_meas: string | null;
    vehicle_name: string;
  };
  cnsg_prty_name_txt: string | null;
  cnsg_sct_sped_org_name_txt: string | null;
  cnsg_tel_cmm_cmp_num_txt: string | null;
  cnsg_pstl_adrs_line_one_txt: string;
  cnsg_pstc_cd: string | null;
  logs_srvc_prv_prty_name_txt: string;
  logs_srvc_prv_sct_sped_org_name_txt: string | null;
  logs_srvc_prv_sct_tel_cmm_cmp_num_txt: string | null;
  item_name_txt: string;
  trsp_cli_prty_name_txt: string;
  vehicle_avb_resource_item_id_created_at: string;
  trsp_cli_tel_cmm_cmp_num_txt: string;
  road_carr_depa_sped_org_name_txt: string;
  total: number;
  trailer: {
    service_no: string;
    service_name: string;
    service_strt_date: string;
    service_strt_time: string;
    service_end_date: string;
    service_end_time: string;
    freight_rate: number;
    car_ctrl_num_id: number | null;
    trailer_license_plt_num_id: string;
    departure_from: string;
    arrival_to: string;
  };
};

export interface ITransportPlanSale {
  price: number;
  status: number;
  departure_from: number;
  arrival_to: number;
  transport_date: string;
  collection_time_from: string;
  collection_time_to: string;
  created_date: string;
  item_name_txt: string;
  trsp_cli_prty_name_txt: string;

  id: number;
  created_user: string;
  updated_user: string;
  updated_date: string;
  req_cns_line_item_id: number;
  operator_id: string;
  operator_code: string;
  trans_plan_id: string;
  transport_code: string;
  transport_name: string;
  operatorName: string;
  collection_date: string;
  trailer_number: number;
  trailer_number_rest: number;
  price_per_unit: number;
  vehicle_condition: number[];
  outer_package_code: number;
  total_length?: string;
  total_width?: string;
  total_height?: string;
  weight?: string;
  special_instructions?: string;
  trans_type: number;
  propose_price?: number;
  propose_depature_time?: string;
  propose_arrival_time?: string;
  istd_totl_vol_meas?: string;
  vol_unt_cd?: number;
  num_unt_cd?: number;
  weig_unt_cd?: number;
  trans_order_id?: number;
  cns_line_item_id?: number;
  shipper_operator_code?: string;
  temperatureRange: [];
}

export interface ITransportShipperSearch {
  id: number;
  day: string;
  price: number;
  status: number;
  giai: string;
  operator_id: string;
  operator_code: string;
  car_info_id: number;
  vehicle_availability_resource_id: number;
  departure_from: number;
  arrival_to: number;
  trip_name: string;
  departure_time_min: string;
  departure_time_max: string;
  arrival_time: string;
  adjustment_price?: number;
  vehicle_type?: number;
  display_order?: number;
  assign_type?: number;
  max_payload: number;
  total_length: number;
  total_width: number;
  total_height: number;
  vehicle_size?: number;
  service_strt_date: string;
  temperature_range?: [];
  cut_off_info_id?: number;
  cut_off_time?: number;
  cut_off_fee: number;
  free_time_info_id?: number;
  free_time_time?: number;
  free_time_fee?: number;
  trans_type?: number;
  operator_name: string;
  tractor_idcr: string;
  car_license_plt_num_id?: string;
  trailer_license_plt_num_id: string;
  service_no: string;
  created_date: string;
  vehicle_name: string;
  propose_trsp_plan: Proposetrspplan[];
}

interface Proposetrspplan {
  id: number;
  trans_type: number;
  operator_id: string;
  operator_name: string;
  cns_line_item_id: number;
  trans_plan_id: string;
  collection_date: string;
  collection_time_from: string;
  collection_time_to: string;
  outer_package_code: number;
  price_per_unit: number;
  status: number;
  total_height: number;
  total_length: number;
  total_width: number;
  trailer_number: number;
  trailer_number_rest: number;
  weight: number;
  arrival_to: number;
  departure_from: number;
  transport_code: string;
  transport_name: string;
  special_instructions?: any;
  vehicle_condition?: any;
  created_date: string;
  shipper_info: Shipperinfo;
  trsp_plan_line_item: [];
}

interface Shipperinfo {
  id: number;
  operator_name: string;
  outer_package_code: string;
  collection_date: string;
  collection_time_from: string;
  collection_time_to: string;
  special_instructions?: string;
}
